### ISSUE TITLE
Not able to run brick_mux regression

### ISSUE THREAD

**Issue by mohit84** [gluster/project-infrastructure#102]
https://build.gluster.org/job/gh_regression-on-demand-multiplex/33/console
GitHub pull request #1751 of commit c56e6c16e9b2332d92b6ed9531d28c81fbcdeb6f, no merge conflicts.
18:59:02 Running as SYSTEM
18:59:03 Setting status of c56e6c16e9b2332d92b6ed9531d28c81fbcdeb6f to PENDING with url https://build.gluster.org/job/gh_regression-on-demand-multiplex/33/ and message: 'Running: brick mux regression'
18:59:03 Using context: Testing: brick mux regression
18:59:03 Building remotely on builder210.aws.gluster.org (centos7) in workspace /home/jenkins/root/workspace/gh_regression-on-demand-multiplex
18:59:03 The recommended git tool is: NONE
18:59:03 No credentials specified
18:59:03 Wiping out workspace first.
18:59:03 Cloning the remote Git repository
18:59:03 Using shallow clone with depth 1
18:59:03 Cloning repository https://github.com/gluster/glusterfs.git
18:59:03  > git init /home/jenkins/root/workspace/gh_regression-on-demand-multiplex # timeout=10
18:59:03 ERROR: Error cloning remote repo 'origin'
18:59:03 hudson.plugins.git.GitException: Could not init /home/jenkins/root/workspace/gh_regression-on-demand-multiplex
18:59:03 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$5.execute(CliGitAPIImpl.java:997)
18:59:03 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$2.execute(CliGitAPIImpl.java:752)
18:59:03 	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$GitCommandMasterToSlaveCallable.call(RemoteGitImpl.java:161)
18:59:03 	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$GitCommandMasterToSlaveCallable.call(RemoteGitImpl.java:154)
18:59:03 	at hudson.remoting.UserRequest.perform(UserRequest.java:211)
18:59:03 	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
18:59:03 	at hudson.remoting.Request$2.run(Request.java:375)
18:59:03 	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:73)
18:59:03 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
18:59:03 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
18:59:03 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
18:59:03 	at java.lang.Thread.run(Thread.java:748)
18:59:03 	Suppressed: hudson.remoting.Channel$CallSiteStackTrace: Remote call to builder210.aws.gluster.org
18:59:03 		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1800)
18:59:03 		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:357)
18:59:03 		at hudson.remoting.Channel.call(Channel.java:1001)
18:59:03 		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.execute(RemoteGitImpl.java:146)
18:59:03 		at sun.reflect.GeneratedMethodAccessor452.invoke(Unknown Source)
18:59:03 		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
18:59:03 		at java.lang.reflect.Method.invoke(Method.java:498)
18:59:03 		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.invoke(RemoteGitImpl.java:132)
18:59:03 		at com.sun.proxy.$Proxy93.execute(Unknown Source)
18:59:03 		at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1219)
18:59:03 		at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1297)
18:59:03 		at hudson.scm.SCM.checkout(SCM.java:505)
18:59:03 		at hudson.model.AbstractProject.checkout(AbstractProject.java:1206)
18:59:03 		at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:574)
18:59:03 		at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
18:59:03 		at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:499)
18:59:03 		at hudson.model.Run.execute(Run.java:1894)
18:59:03 		at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
18:59:03 		at hudson.model.ResourceController.execute(ResourceController.java:97)
18:59:03 		at hudson.model.Executor.run(Executor.java:428)
18:59:03 Caused by: hudson.plugins.git.GitException: Command "git init /home/jenkins/root/workspace/gh_regression-on-demand-multiplex" returned status code 1:
18:59:03 stdout: 
18:59:03 stderr: /home/jenkins/root/workspace/gh_regression-on-demand-multiplex/.git: No space left on device
18:59:03 
18:59:03 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2450)
18:59:03 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2380)
18:59:03 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2376)
18:59:03 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommand(CliGitAPIImpl.java:1923)
18:59:03 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$5.execute(CliGitAPIImpl.java:995)
18:59:03 	... 11 more
18:59:03 ERROR: Error cloning remote repo 'origin'
18:59:03 Retrying after 10 seconds
18:59:13 The recommended git tool is: NONE
18:59:14 No credentials specified
18:59:14 Wiping out workspace first.
18:59:14 Cloning the remote Git repository
18:59:14 Using shallow clone with depth 1
18:59:14 Cloning repository https://github.com/gluster/glusterfs.git
18:59:14  > git init /home/jenkins/root/workspace/gh_regression-on-demand-multiplex # timeout=10
18:59:14 ERROR: Error cloning remote repo 'origin'
18:59:14 hudson.plugins.git.GitException: Could not init /home/jenkins/root/workspace/gh_regression-on-demand-multiplex
18:59:14 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$5.execute(CliGitAPIImpl.java:997)
18:59:14 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$2.execute(CliGitAPIImpl.java:752)
18:59:14 	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$GitCommandMasterToSlaveCallable.call(RemoteGitImpl.java:161)
18:59:14 	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$GitCommandMasterToSlaveCallable.call(RemoteGitImpl.java:154)
18:59:14 	at hudson.remoting.UserRequest.perform(UserRequest.java:211)
18:59:14 	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
18:59:14 	at hudson.remoting.Request$2.run(Request.java:375)
18:59:14 	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:73)
18:59:14 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
18:59:14 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
18:59:14 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
18:59:14 	at java.lang.Thread.run(Thread.java:748)
18:59:14 	Suppressed: hudson.remoting.Channel$CallSiteStackTrace: Remote call to builder210.aws.gluster.org
18:59:14 		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1800)
18:59:14 		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:357)
18:59:14 		at hudson.remoting.Channel.call(Channel.java:1001)
18:59:14 		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.execute(RemoteGitImpl.java:146)
18:59:14 		at sun.reflect.GeneratedMethodAccessor452.invoke(Unknown Source)
18:59:14 		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
18:59:14 		at java.lang.reflect.Method.invoke(Method.java:498)
18:59:14 		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.invoke(RemoteGitImpl.java:132)
18:59:14 		at com.sun.proxy.$Proxy93.execute(Unknown Source)
18:59:14 		at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1219)
18:59:14 		at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1297)
18:59:14 		at hudson.scm.SCM.checkout(SCM.java:505)
18:59:14 		at hudson.model.AbstractProject.checkout(AbstractProject.java:1206)
18:59:14 		at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:574)
18:59:14 		at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
18:59:14 		at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:499)
18:59:14 		at hudson.model.Run.execute(Run.java:1894)
18:59:14 		at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
18:59:14 		at hudson.model.ResourceController.execute(ResourceController.java:97)
18:59:14 		at hudson.model.Executor.run(Executor.java:428)
18:59:14 Caused by: hudson.plugins.git.GitException: Command "git init /home/jenkins/root/workspace/gh_regression-on-demand-multiplex" returned status code 1:
18:59:14 stdout: 
18:59:14 stderr: /home/jenkins/root/workspace/gh_regression-on-demand-multiplex/.git: No space left on device
18:59:14 
18:59:14 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2450)
18:59:14 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2380)
18:59:14 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2376)
18:59:14 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommand(CliGitAPIImpl.java:1923)
18:59:14 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$5.execute(CliGitAPIImpl.java:995)
18:59:14 	... 11 more
18:59:14 ERROR: Error cloning remote repo 'origin'
18:59:14 Retrying after 10 seconds
18:59:24 The recommended git tool is: NONE
18:59:24 No credentials specified
18:59:24 Wiping out workspace first.
18:59:24 Cloning the remote Git repository
18:59:24 Using shallow clone with depth 1
18:59:24 Cloning repository https://github.com/gluster/glusterfs.git
18:59:24  > git init /home/jenkins/root/workspace/gh_regression-on-demand-multiplex # timeout=10
18:59:24 ERROR: Error cloning remote repo 'origin'
18:59:24 hudson.plugins.git.GitException: Could not init /home/jenkins/root/workspace/gh_regression-on-demand-multiplex
18:59:24 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$5.execute(CliGitAPIImpl.java:997)
18:59:24 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$2.execute(CliGitAPIImpl.java:752)
18:59:24 	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$GitCommandMasterToSlaveCallable.call(RemoteGitImpl.java:161)
18:59:24 	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$GitCommandMasterToSlaveCallable.call(RemoteGitImpl.java:154)
18:59:24 	at hudson.remoting.UserRequest.perform(UserRequest.java:211)
18:59:24 	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
18:59:24 	at hudson.remoting.Request$2.run(Request.java:375)
18:59:24 	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:73)
18:59:24 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
18:59:24 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
18:59:24 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
18:59:24 	at java.lang.Thread.run(Thread.java:748)
18:59:24 	Suppressed: hudson.remoting.Channel$CallSiteStackTrace: Remote call to builder210.aws.gluster.org
18:59:24 		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1800)
18:59:24 		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:357)
18:59:24 		at hudson.remoting.Channel.call(Channel.java:1001)
18:59:24 		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.execute(RemoteGitImpl.java:146)
18:59:24 		at sun.reflect.GeneratedMethodAccessor452.invoke(Unknown Source)
18:59:24 		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
18:59:24 		at java.lang.reflect.Method.invoke(Method.java:498)
18:59:24 		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.invoke(RemoteGitImpl.java:132)
18:59:24 		at com.sun.proxy.$Proxy93.execute(Unknown Source)
18:59:24 		at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1219)
18:59:24 		at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1297)
18:59:24 		at hudson.scm.SCM.checkout(SCM.java:505)
18:59:24 		at hudson.model.AbstractProject.checkout(AbstractProject.java:1206)
18:59:24 		at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:574)
18:59:24 		at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
18:59:24 		at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:499)
18:59:24 		at hudson.model.Run.execute(Run.java:1894)
18:59:24 		at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
18:59:24 		at hudson.model.ResourceController.execute(ResourceController.java:97)
18:59:24 		at hudson.model.Executor.run(Executor.java:428)
18:59:24 Caused by: hudson.plugins.git.GitException: Command "git init /home/jenkins/root/workspace/gh_regression-on-demand-multiplex" returned status code 1:
18:59:24 stdout: 
18:59:24 stderr: /home/jenkins/root/workspace/gh_regression-on-demand-multiplex/.git: No space left on device
18:59:24 
18:59:24 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2450)
18:59:24 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2380)
18:59:24 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2376)
18:59:24 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommand(CliGitAPIImpl.java:1923)
18:59:24 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$5.execute(CliGitAPIImpl.java:995)
18:59:24 	... 11 more
18:59:24 ERROR: Error cloning remote repo 'origin'
18:59:24 Retrying after 10 seconds
18:59:34 The recommended git tool is: NONE
18:59:34 No credentials specified
18:59:34 Wiping out workspace first.
18:59:34 Cloning the remote Git repository
18:59:34 Using shallow clone with depth 1
18:59:34 Cloning repository https://github.com/gluster/glusterfs.git
18:59:34  > git init /home/jenkins/root/workspace/gh_regression-on-demand-multiplex # timeout=10
18:59:34 ERROR: Error cloning remote repo 'origin'
18:59:34 hudson.plugins.git.GitException: Could not init /home/jenkins/root/workspace/gh_regression-on-demand-multiplex
18:59:34 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$5.execute(CliGitAPIImpl.java:997)
18:59:34 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$2.execute(CliGitAPIImpl.java:752)
18:59:34 	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$GitCommandMasterToSlaveCallable.call(RemoteGitImpl.java:161)
18:59:34 	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$GitCommandMasterToSlaveCallable.call(RemoteGitImpl.java:154)
18:59:34 	at hudson.remoting.UserRequest.perform(UserRequest.java:211)
18:59:34 	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
18:59:34 	at hudson.remoting.Request$2.run(Request.java:375)
18:59:34 	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:73)
18:59:34 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
18:59:34 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
18:59:34 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
18:59:34 	at java.lang.Thread.run(Thread.java:748)
18:59:34 	Suppressed: hudson.remoting.Channel$CallSiteStackTrace: Remote call to builder210.aws.gluster.org
18:59:34 		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1800)
18:59:34 		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:357)
18:59:34 		at hudson.remoting.Channel.call(Channel.java:1001)
18:59:34 		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.execute(RemoteGitImpl.java:146)
18:59:34 		at sun.reflect.GeneratedMethodAccessor452.invoke(Unknown Source)
18:59:34 		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
18:59:34 		at java.lang.reflect.Method.invoke(Method.java:498)
18:59:34 		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.invoke(RemoteGitImpl.java:132)
18:59:34 		at com.sun.proxy.$Proxy93.execute(Unknown Source)
18:59:34 		at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1219)
18:59:34 		at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1297)
18:59:34 		at hudson.scm.SCM.checkout(SCM.java:505)
18:59:34 		at hudson.model.AbstractProject.checkout(AbstractProject.java:1206)
18:59:34 		at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:574)
18:59:34 		at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
18:59:34 		at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:499)
18:59:34 		at hudson.model.Run.execute(Run.java:1894)
18:59:34 		at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
18:59:34 		at hudson.model.ResourceController.execute(ResourceController.java:97)
18:59:34 		at hudson.model.Executor.run(Executor.java:428)
18:59:34 Caused by: hudson.plugins.git.GitException: Command "git init /home/jenkins/root/workspace/gh_regression-on-demand-multiplex" returned status code 1:
18:59:34 stdout: 
18:59:34 stderr: /home/jenkins/root/workspace/gh_regression-on-demand-multiplex/.git: No space left on device
18:59:34 
18:59:34 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2450)
18:59:34 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2380)
18:59:34 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2376)
18:59:34 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommand(CliGitAPIImpl.java:1923)
18:59:34 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$5.execute(CliGitAPIImpl.java:995)
18:59:34 	... 11 more
18:59:34 ERROR: Error cloning remote repo 'origin'
18:59:34 Performing Post build task...
18:59:34 Could not match :Build was aborted  : False
18:59:34 Logical operation result is FALSE
18:59:34 Skipping script  : #!/bin/bash
18:59:34 
18:59:34 ARCHIVE_BASE="/archives"
18:59:34 ARCHIVED_LOGS="logs"
18:59:34 UNIQUE_ID="${JOB_NAME}-${BUILD_ID}"
18:59:34 SERVER=$(hostname)
18:59:34 
18:59:34 filename="${ARCHIVED_LOGS}/glusterfs-logs-${UNIQUE_ID}.tgz"
18:59:34 sudo -E tar -czf "${ARCHIVE_BASE}/${filename}" /var/log/glusterfs /var/log/messages*;
18:59:34 echo "Logs archived in http://${SERVER}/${filename}"
18:59:34 sudo reboot
18:59:34 
18:59:34 END OF POST BUILD TASK 	: 0
18:59:34 Archiving artifacts
18:59:34 Setting status of c56e6c16e9b2332d92b6ed9531d28c81fbcdeb6f to FAILURE with url https://build.gluster.org/job/gh_regression-on-demand-multiplex/33/ and message: 'FAIL - please fix for merge
18:59:34  '
18:59:34 Using context: Testing: brick mux regression
18:59:35 Finished: FAILURE

**Comment by mscherer** [comment]
Seems some tests filled the disk again. i cleaned the server for now, but if that happen a 3rd time, we would have to reinstall and investigate if that's a specific patch that create the problem.

**Comment by mohit84** [comment]
Not able to run brick_mux regression
https://build.gluster.org/job/gh_regression-on-demand-multiplex/41/console
https://build.gluster.org/job/gh_regression-on-demand-multiplex/42/console

**Comment by mscherer** [comment]
So it seems that https://build.gluster.org/job/gh_regression-on-demand-multiplex/38/console broke the builder.

The multiplex test take more than 7h30 , which make Jenkins abort the job, and then it leave the builder in a incorrect state.

**Comment by mohit84** [comment]
Can i run a brick_mux regression now?

**Comment by mscherer** [comment]
It would likely fail again, and I want to investigate a bit more. I am curious on why it take so long, I can't see why multiplex would result into that.

**Comment by mohit84** [comment]
It seems brick_mux is not enabled while running a brick_mux regression job.
https://build.gluster.org/job/gh_regression-on-demand-multiplex/43/console
As we can see "Enable Brick Mux     : no" is showing no on the console, we need to change the script.

@deepshikhaaa 
Do you have any idea how a script is changed, for brick_mux regression the value of flag value should be yes.

**Comment by deepshikhaaa** [comment]
I noticed today that the PR https://github.com/gluster/glusterfs-patch-acceptance-tests/pull/203 was never merged. I have merged it now. Let's see if the issue comes up again.
