### ISSUE TITLE
Testing: strfmt errors in a 32 build — FAIL - please fix for merge 

### ISSUE THREAD

**Issue by itisravi** [gluster/project-infrastructure#113]
Smoke check keeps failing for https://github.com/gluster/glusterfs/pull/2009

Artefacts:
https://build.gluster.org/job/gh_strfmt_errors/779/console
https://build.gluster.org/job/gh_strfmt_errors/781/console

```
21:12:56 GitHub pull request #2009 of commit ad86362bbb70266018123dff71ba004a7d702ae7, no merge conflicts.
21:12:56 Running as SYSTEM
21:12:56 Setting status of ad86362bbb70266018123dff71ba004a7d702ae7 to PENDING with url https://build.gluster.org/job/gh_strfmt_errors/781/ and message: 'Running: strfmt errors in a 32 build'
21:12:56 Using context: Testing: strfmt errors in a 32 build
21:12:57 Building remotely on builder-f32-1.int.aws.gluster.org (fedora32) in workspace /home/jenkins/root/workspace/gh_strfmt_errors
21:12:57 The recommended git tool is: NONE
21:12:57 No credentials specified
21:12:57 Wiping out workspace first.
21:12:57 Also:   java.nio.file.FileSystemException: /home/jenkins/root/workspace/gh_strfmt_errors/RPMS/fc33/i686/state.log: Operation not permitted
21:12:57 		at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91)
21:12:57 		at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
21:12:57 		at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
21:12:57 		at sun.nio.fs.UnixFileAttributeViews$Posix.setMode(UnixFileAttributeViews.java:238)
21:12:57 		at sun.nio.fs.UnixFileAttributeViews$Posix.setPermissions(UnixFileAttributeViews.java:260)
21:12:57 		at java.nio.file.Files.setPosixFilePermissions(Files.java:2045)
21:12:57 		at jenkins.util.io.PathRemover.makeWritable(PathRemover.java:286)
21:12:57 		at jenkins.util.io.PathRemover.makeRemovable(PathRemover.java:259)
21:12:57 		at jenkins.util.io.PathRemover.removeOrMakeRemovableThenRemove(PathRemover.java:239)
21:12:57 		at jenkins.util.io.PathRemover.tryRemoveFile(PathRemover.java:205)
21:12:57 		at jenkins.util.io.PathRemover.tryRemoveRecursive(PathRemover.java:216)
21:12:57 		at jenkins.util.io.PathRemover.tryRemoveDirectoryContents(PathRemover.java:226)
21:12:57 		at jenkins.util.io.PathRemover.tryRemoveRecursive(PathRemover.java:215)
21:12:57 		at jenkins.util.io.PathRemover.tryRemoveDirectoryContents(PathRemover.java:226)
21:12:57 		at jenkins.util.io.PathRemover.tryRemoveRecursive(PathRemover.java:215)
21:12:57 		at jenkins.util.io.PathRemover.tryRemoveDirectoryContents(PathRemover.java:226)
21:12:57 		at jenkins.util.io.PathRemover.tryRemoveRecursive(PathRemover.java:215)
21:12:57 		at jenkins.util.io.PathRemover.tryRemoveDirectoryContents(PathRemover.java:226)
21:12:57 		at jenkins.util.io.PathRemover.forceRemoveDirectoryContents(PathRemover.java:87)
```

@mscherer @deepshikhaaa  Please take a look.

**Comment by mscherer** [comment]
```
# ls -l /home/jenkins/root/workspace/gh_strfmt_errors/RPMS/fc33/i686/state.log
-rw-rw-r--. 1 jenkins jenkins 1107 Jan 14 09:03 /home/jenkins/root/workspace/gh_strfmt_errors/RPMS/fc33/i686/state.log
```

I do not understand why it doesn't wipe that :/

I removed manually, let's see if this happen again.

**Comment by mscherer** [comment]
Seems to be ok cf https://build.gluster.org/job/gh_strfmt_errors/783/console

**Comment by deepshikhaaa** [comment]
It occurred again on builder-f32-1.int.aws.gluster.org. 

`[root@builder-f32-1 ~]# ls -l /home/jenkins/root/workspace/gh_strfmt_errors/RPMS/fc33/i686/state.log
-rw-rw-r--. 1 root root 962 Jan 18 08:53 /home/jenkins/root/workspace/gh_strfmt_errors/RPMS/fc33/i686/state.log`

I deleted state.log now. But we need to find what causes such issue on builders.

**Comment by BarakSason** [comment]
Ran into this on https://github.com/gluster/glusterfs/pull/2026 (https://build.gluster.org/job/gh_strfmt_errors/832/console)

**Comment by deepshikhaaa** [comment]
Fix: https://github.com/gluster/build-jobs/pull/65
