### ISSUE TITLE
centos-7 regression failing

### ISSUE THREAD

**Issue by itisravi** [gluster/project-infrastructure#128]
Build #1143 (May 4, 2021 7:27:18 AM) 
https://build.gluster.org/job/gh_centos7-regression/1143/console

```
12:57:18 GitHub pull request #2371 of commit 9c93837defbc494849d92ea2afc57bcf9d3fd29e, no merge conflicts.
12:57:18 Running as SYSTEM
12:57:18 Setting status of 9c93837defbc494849d92ea2afc57bcf9d3fd29e to PENDING with url https://build.gluster.org/job/gh_centos7-regression/1143/ and message: 'Running: regression test suite'
12:57:18 Using context: Testing: regression test suite
12:57:18 Building remotely on builder-c7-3.int.aws.gluster.org (centos7) in workspace /home/jenkins/root/workspace/gh_centos7-regression
12:57:18 The recommended git tool is: NONE
12:57:18 Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to builder-c7-3.int.aws.gluster.org
12:57:18 		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1800)
12:57:18 		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:356)
12:57:18 		at hudson.remoting.Channel.call(Channel.java:1001)
12:57:18 		at hudson.FilePath.act(FilePath.java:1158)
12:57:18 		at hudson.FilePath.act(FilePath.java:1147)
12:57:18 		at org.jenkinsci.plugins.gitclient.Git.getClient(Git.java:121)
12:57:18 		at hudson.plugins.git.GitSCM.createClient(GitSCM.java:904)
12:57:18 		at hudson.plugins.git.GitSCM.createClient(GitSCM.java:835)
12:57:18 		at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1288)
12:57:18 		at hudson.scm.SCM.checkout(SCM.java:505)
12:57:18 		at hudson.model.AbstractProject.checkout(AbstractProject.java:1204)
12:57:18 		at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:636)
12:57:18 		at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
12:57:18 		at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:508)
12:57:18 		at hudson.model.Run.execute(Run.java:1907)
12:57:18 		at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
12:57:18 		at hudson.model.ResourceController.execute(ResourceController.java:97)
12:57:18 		at hudson.model.Executor.run(Executor.java:429)
12:57:18 java.lang.NoClassDefFoundError: Could not initialize class com.sun.proxy.$Proxy8
12:57:18 	at sun.reflect.GeneratedConstructorAccessor5.newInstance(Unknown Source)
12:57:18 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
12:57:18 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
12:57:18 	at java.lang.reflect.Proxy.newProxyInstance(Proxy.java:739)
12:57:18 	at hudson.remoting.RemoteInvocationHandler.wrap(RemoteInvocationHandler.java:169)
12:57:18 	at hudson.remoting.Channel.export(Channel.java:813)
12:57:18 	at hudson.remoting.Channel.export(Channel.java:776)
12:57:18 	at org.jenkinsci.plugins.gitclient.LegacyCompatibleGitAPIImpl.writeReplace(LegacyCompatibleGitAPIImpl.java:204)
12:57:18 	at sun.reflect.GeneratedMethodAccessor19.invoke(Unknown Source)
12:57:18 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
12:57:18 	at java.lang.reflect.Method.invoke(Method.java:498)
12:57:18 	at java.io.ObjectStreamClass.invokeWriteReplace(ObjectStreamClass.java:1244)
12:57:18 	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1136)
12:57:18 	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
12:57:18 	at hudson.remoting.UserRequest._serialize(UserRequest.java:263)
12:57:18 	at hudson.remoting.UserRequest.serialize(UserRequest.java:272)
12:57:18 	at hudson.remoting.UserRequest.perform(UserRequest.java:222)
12:57:18 	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
12:57:18 	at hudson.remoting.Request$2.run(Request.java:376)
12:57:18 	at hudson.remoting.InterceptingExecutorService.lambda$wrap$0(InterceptingExecutorService.java:78)
12:57:18 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
12:57:18 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
12:57:18 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
12:57:18 	at java.lang.Thread.run(Thread.java:748)
12:57:18 Caused: java.io.IOException: Remote call on builder-c7-3.int.aws.gluster.org failed
12:57:18 	at hudson.remoting.Channel.call(Channel.java:1007)
12:57:18 	at hudson.FilePath.act(FilePath.java:1158)
12:57:18 	at hudson.FilePath.act(FilePath.java:1147)
12:57:18 	at org.jenkinsci.plugins.gitclient.Git.getClient(Git.java:121)
12:57:18 	at hudson.plugins.git.GitSCM.createClient(GitSCM.java:904)
12:57:18 	at hudson.plugins.git.GitSCM.createClient(GitSCM.java:835)
12:57:18 	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1288)
12:57:18 	at hudson.scm.SCM.checkout(SCM.java:505)
12:57:18 	at hudson.model.AbstractProject.checkout(AbstractProject.java:1204)
12:57:18 	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:636)
12:57:18 	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
12:57:18 	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:508)
12:57:18 	at hudson.model.Run.execute(Run.java:1907)
12:57:18 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
12:57:18 	at hudson.model.ResourceController.execute(ResourceController.java:97)
12:57:18 	at hudson.model.Executor.run(Executor.java:429)
12:57:18 Retrying after 10 seconds
12:57:28 The recommended git tool is: NONE
12:57:28 Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to builder-c7-3.int.aws.gluster.org
12:57:28 		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1800)
12:57:28 		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:356)
12:57:28 		at hudson.remoting.Channel.call(Channel.java:1001)
12:57:28 		at hudson.FilePath.act(FilePath.java:1158)
12:57:28 		at hudson.FilePath.act(FilePath.java:1147)
12:57:28 		at org.jenkinsci.plugins.gitclient.Git.getClient(Git.java:121)
12:57:28 		at hudson.plugins.git.GitSCM.createClient(GitSCM.java:904)
12:57:28 		at hudson.plugins.git.GitSCM.createClient(GitSCM.java:835)
12:57:28 		at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1288)
12:57:28 		at hudson.scm.SCM.checkout(SCM.java:505)
12:57:28 		at hudson.model.AbstractProject.checkout(AbstractProject.java:1204)
12:57:28 		at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:636)
12:57:28 		at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
12:57:28 		at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:508)
12:57:28 		at hudson.model.Run.execute(Run.java:1907)
12:57:28 		at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
12:57:28 		at hudson.model.ResourceController.execute(ResourceController.java:97)
12:57:28 		at hudson.model.Executor.run(Executor.java:429)
12:57:28 java.lang.NoClassDefFoundError: Could not initialize class com.sun.proxy.$Proxy8
12:57:28 	at sun.reflect.GeneratedConstructorAccessor5.newInstance(Unknown Source)
12:57:28 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
12:57:28 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
12:57:28 	at java.lang.reflect.Proxy.newProxyInstance(Proxy.java:739)
12:57:28 	at hudson.remoting.RemoteInvocationHandler.wrap(RemoteInvocationHandler.java:169)
12:57:28 	at hudson.remoting.Channel.export(Channel.java:813)
12:57:28 	at hudson.remoting.Channel.export(Channel.java:776)
12:57:28 	at org.jenkinsci.plugins.gitclient.LegacyCompatibleGitAPIImpl.writeReplace(LegacyCompatibleGitAPIImpl.java:204)
12:57:28 	at sun.reflect.GeneratedMethodAccessor19.invoke(Unknown Source)
12:57:28 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
12:57:28 	at java.lang.reflect.Method.invoke(Method.java:498)
12:57:28 	at java.io.ObjectStreamClass.invokeWriteReplace(ObjectStreamClass.java:1244)
12:57:28 	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1136)
12:57:28 	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
12:57:28 	at hudson.remoting.UserRequest._serialize(UserRequest.java:263)
12:57:28 	at hudson.remoting.UserRequest.serialize(UserRequest.java:272)
12:57:28 	at hudson.remoting.UserRequest.perform(UserRequest.java:222)
12:57:28 	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
12:57:28 	at hudson.remoting.Request$2.run(Request.java:376)
12:57:28 	at hudson.remoting.InterceptingExecutorService.lambda$wrap$0(InterceptingExecutorService.java:78)
12:57:28 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
12:57:28 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
12:57:28 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
12:57:28 	at java.lang.Thread.run(Thread.java:748)
12:57:28 Caused: java.io.IOException: Remote call on builder-c7-3.int.aws.gluster.org failed
12:57:28 	at hudson.remoting.Channel.call(Channel.java:1007)
12:57:28 	at hudson.FilePath.act(FilePath.java:1158)
12:57:28 	at hudson.FilePath.act(FilePath.java:1147)
12:57:28 	at org.jenkinsci.plugins.gitclient.Git.getClient(Git.java:121)
12:57:28 	at hudson.plugins.git.GitSCM.createClient(GitSCM.java:904)
12:57:28 	at hudson.plugins.git.GitSCM.createClient(GitSCM.java:835)
12:57:28 	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1288)
12:57:28 	at hudson.scm.SCM.checkout(SCM.java:505)
12:57:28 	at hudson.model.AbstractProject.checkout(AbstractProject.java:1204)
12:57:28 	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:636)
12:57:28 	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
12:57:28 	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:508)
12:57:28 	at hudson.model.Run.execute(Run.java:1907)
12:57:28 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
12:57:28 	at hudson.model.ResourceController.execute(ResourceController.java:97)
12:57:28 	at hudson.model.Executor.run(Executor.java:429)
12:57:28 Retrying after 10 seconds
12:57:38 The recommended git tool is: NONE
12:57:38 Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to builder-c7-3.int.aws.gluster.org
12:57:38 		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1800)
12:57:38 		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:356)
12:57:38 		at hudson.remoting.Channel.call(Channel.java:1001)
12:57:38 		at hudson.FilePath.act(FilePath.java:1158)
12:57:38 		at hudson.FilePath.act(FilePath.java:1147)
12:57:38 		at org.jenkinsci.plugins.gitclient.Git.getClient(Git.java:121)
12:57:38 		at hudson.plugins.git.GitSCM.createClient(GitSCM.java:904)
12:57:38 		at hudson.plugins.git.GitSCM.createClient(GitSCM.java:835)
12:57:38 		at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1288)
12:57:38 		at hudson.scm.SCM.checkout(SCM.java:505)
12:57:38 		at hudson.model.AbstractProject.checkout(AbstractProject.java:1204)
12:57:38 		at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:636)
12:57:38 		at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
12:57:38 		at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:508)
12:57:38 		at hudson.model.Run.execute(Run.java:1907)
12:57:38 		at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
12:57:38 		at hudson.model.ResourceController.execute(ResourceController.java:97)
12:57:38 		at hudson.model.Executor.run(Executor.java:429)
12:57:38 java.lang.NoClassDefFoundError: Could not initialize class com.sun.proxy.$Proxy8
12:57:38 	at sun.reflect.GeneratedConstructorAccessor5.newInstance(Unknown Source)
12:57:38 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
12:57:38 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
12:57:38 	at java.lang.reflect.Proxy.newProxyInstance(Proxy.java:739)
12:57:38 	at hudson.remoting.RemoteInvocationHandler.wrap(RemoteInvocationHandler.java:169)
12:57:38 	at hudson.remoting.Channel.export(Channel.java:813)
12:57:38 	at hudson.remoting.Channel.export(Channel.java:776)
12:57:38 	at org.jenkinsci.plugins.gitclient.LegacyCompatibleGitAPIImpl.writeReplace(LegacyCompatibleGitAPIImpl.java:204)
12:57:38 	at sun.reflect.GeneratedMethodAccessor19.invoke(Unknown Source)
12:57:38 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
12:57:38 	at java.lang.reflect.Method.invoke(Method.java:498)
12:57:38 	at java.io.ObjectStreamClass.invokeWriteReplace(ObjectStreamClass.java:1244)
12:57:38 	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1136)
12:57:38 	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
12:57:38 	at hudson.remoting.UserRequest._serialize(UserRequest.java:263)
12:57:38 	at hudson.remoting.UserRequest.serialize(UserRequest.java:272)
12:57:38 	at hudson.remoting.UserRequest.perform(UserRequest.java:222)
12:57:38 	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
12:57:38 	at hudson.remoting.Request$2.run(Request.java:376)
12:57:38 	at hudson.remoting.InterceptingExecutorService.lambda$wrap$0(InterceptingExecutorService.java:78)
12:57:38 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
12:57:38 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
12:57:38 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
12:57:38 	at java.lang.Thread.run(Thread.java:748)
12:57:38 Caused: java.io.IOException: Remote call on builder-c7-3.int.aws.gluster.org failed
12:57:38 	at hudson.remoting.Channel.call(Channel.java:1007)
12:57:38 	at hudson.FilePath.act(FilePath.java:1158)
12:57:38 	at hudson.FilePath.act(FilePath.java:1147)
12:57:38 	at org.jenkinsci.plugins.gitclient.Git.getClient(Git.java:121)
12:57:38 	at hudson.plugins.git.GitSCM.createClient(GitSCM.java:904)
12:57:38 	at hudson.plugins.git.GitSCM.createClient(GitSCM.java:835)
12:57:38 	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1288)
12:57:38 	at hudson.scm.SCM.checkout(SCM.java:505)
12:57:38 	at hudson.model.AbstractProject.checkout(AbstractProject.java:1204)
12:57:38 	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:636)
12:57:38 	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
12:57:38 	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:508)
12:57:38 	at hudson.model.Run.execute(Run.java:1907)
12:57:38 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
12:57:38 	at hudson.model.ResourceController.execute(ResourceController.java:97)
12:57:38 	at hudson.model.Executor.run(Executor.java:429)
12:57:38 Retrying after 10 seconds
12:57:49 The recommended git tool is: NONE
12:57:49 Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to builder-c7-3.int.aws.gluster.org
12:57:49 		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1800)
12:57:49 		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:356)
12:57:49 		at hudson.remoting.Channel.call(Channel.java:1001)
12:57:49 		at hudson.FilePath.act(FilePath.java:1158)
12:57:49 		at hudson.FilePath.act(FilePath.java:1147)
12:57:49 		at org.jenkinsci.plugins.gitclient.Git.getClient(Git.java:121)
12:57:49 		at hudson.plugins.git.GitSCM.createClient(GitSCM.java:904)
12:57:49 		at hudson.plugins.git.GitSCM.createClient(GitSCM.java:835)
12:57:49 		at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1288)
12:57:49 		at hudson.scm.SCM.checkout(SCM.java:505)
12:57:49 		at hudson.model.AbstractProject.checkout(AbstractProject.java:1204)
12:57:49 		at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:636)
12:57:49 		at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
12:57:49 		at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:508)
12:57:49 		at hudson.model.Run.execute(Run.java:1907)
12:57:49 		at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
12:57:49 		at hudson.model.ResourceController.execute(ResourceController.java:97)
12:57:49 		at hudson.model.Executor.run(Executor.java:429)
12:57:49 java.lang.NoClassDefFoundError: Could not initialize class com.sun.proxy.$Proxy8
12:57:49 	at sun.reflect.GeneratedConstructorAccessor5.newInstance(Unknown Source)
12:57:49 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
12:57:49 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
12:57:49 	at java.lang.reflect.Proxy.newProxyInstance(Proxy.java:739)
12:57:49 	at hudson.remoting.RemoteInvocationHandler.wrap(RemoteInvocationHandler.java:169)
12:57:49 	at hudson.remoting.Channel.export(Channel.java:813)
12:57:49 	at hudson.remoting.Channel.export(Channel.java:776)
12:57:49 	at org.jenkinsci.plugins.gitclient.LegacyCompatibleGitAPIImpl.writeReplace(LegacyCompatibleGitAPIImpl.java:204)
12:57:49 	at sun.reflect.GeneratedMethodAccessor19.invoke(Unknown Source)
12:57:49 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
12:57:49 	at java.lang.reflect.Method.invoke(Method.java:498)
12:57:49 	at java.io.ObjectStreamClass.invokeWriteReplace(ObjectStreamClass.java:1244)
12:57:49 	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1136)
12:57:49 	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
12:57:49 	at hudson.remoting.UserRequest._serialize(UserRequest.java:263)
12:57:49 	at hudson.remoting.UserRequest.serialize(UserRequest.java:272)
12:57:49 	at hudson.remoting.UserRequest.perform(UserRequest.java:222)
12:57:49 	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
12:57:49 	at hudson.remoting.Request$2.run(Request.java:376)
12:57:49 	at hudson.remoting.InterceptingExecutorService.lambda$wrap$0(InterceptingExecutorService.java:78)
12:57:49 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
12:57:49 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
12:57:49 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
12:57:49 	at java.lang.Thread.run(Thread.java:748)
12:57:49 Caused: java.io.IOException: Remote call on builder-c7-3.int.aws.gluster.org failed
12:57:49 	at hudson.remoting.Channel.call(Channel.java:1007)
12:57:49 	at hudson.FilePath.act(FilePath.java:1158)
12:57:49 	at hudson.FilePath.act(FilePath.java:1147)
12:57:49 	at org.jenkinsci.plugins.gitclient.Git.getClient(Git.java:121)
12:57:49 	at hudson.plugins.git.GitSCM.createClient(GitSCM.java:904)
12:57:49 	at hudson.plugins.git.GitSCM.createClient(GitSCM.java:835)
12:57:49 	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1288)
12:57:49 	at hudson.scm.SCM.checkout(SCM.java:505)
12:57:49 	at hudson.model.AbstractProject.checkout(AbstractProject.java:1204)
12:57:49 	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:636)
12:57:49 	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
12:57:49 	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:508)
12:57:49 	at hudson.model.Run.execute(Run.java:1907)
12:57:49 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
12:57:49 	at hudson.model.ResourceController.execute(ResourceController.java:97)
12:57:49 	at hudson.model.Executor.run(Executor.java:429)
12:57:49 Performing Post build task...
12:57:49 Could not match :Build was aborted  : False
12:57:49 Logical operation result is FALSE
12:57:49 Skipping script  : #!/bin/bash
12:57:49 
12:57:49 UNIQUE_ID="${JOB_NAME}-${BUILD_ID}"
12:57:49 filename="glusterfs-logs-${UNIQUE_ID}.tgz"
12:57:49 sudo -E tar -czf "${filename}" /var/log/glusterfs /var/log/messages*;
12:57:49 scp -o "UserKnownHostsFile=/dev/null" -o "StrictHostKeyChecking=no" -i "$LOG_KEY" "${filename}" "_logs-collector@logs.aws.gluster.org:/var/www/glusterfs-logs/$JOB_NAME-$BUILD_ID.tgz" || true
12:57:49 echo "Logs are archived in https://logs.aws.gluster.org/$JOB_NAME-$BUILD_ID.tgz"
12:57:49 # do clean up after a regression test suite is run
12:57:49 sudo -E bash /opt/qa/cleanup.sh
12:57:49 # make sure that every file/diretory belongs to jenkins
12:57:49 sudo chown -R jenkins:jenkins $WORKSPACE
12:57:49 
12:57:49 sudo reboot
12:57:49 END OF POST BUILD TASK 	: 0
12:57:49 Archiving artifacts
12:57:49 Setting status of 9c93837defbc494849d92ea2afc57bcf9d3fd29e to FAILURE with url https://build.gluster.org/job/gh_centos7-regression/1143/ and message: 'FAIL - please fix for merge
12:57:49  '
12:57:49 Using context: Testing: regression test suite
12:57:49 Finished: FAILURE
```

**Comment by mscherer** [comment]
Closing, since C7 is now running, and the linked build is no longer here.
