### ISSUE TITLE
Facing issue while pushing changes to https://review.gluster.org/

### ISSUE THREAD

**Issue by vh05** [gluster/project-infrastructure#87]
Facing below error during a push to remote. It was all working fine till yesterday.

```
 ! [remote rejected]     HEAD -> refs/for/master/ref-1479 (internal server error: Error inserting change/patchset)
error: failed to push some refs to 'ssh://VHariharmath-rh@review.gluster.org/glusterfs'
```

**Comment by vh05** [comment]
I also tried adding ssh keys on the remote but still, the error persists.

**Comment by mscherer** [comment]
I see that in the log:
```
[2020-10-06 14:33:49,219] [ReceiveCommits-1] ERROR com.google.gerrit.server.git.receive.ReceiveCommits : [glusterfs-1601994822688-f7a9f49f]Can't insert change/patch set for glusterfs
com.google.gerrit.extensions.restapi.RestApiException: Error inserting change/patchset
	at com.google.gerrit.server.git.receive.ReceiveCommits$1.apply(ReceiveCommits.java:288)
	at com.google.gerrit.server.git.receive.ReceiveCommits$1.apply(ReceiveCommits.java:279)
	at com.google.gerrit.server.git.receive.ReceiveCommits.insertChangesAndPatchSets(ReceiveCommits.java:728)
	at com.google.gerrit.server.git.receive.ReceiveCommits.processCommands(ReceiveCommits.java:551)
	at com.google.gerrit.server.git.receive.AsyncReceiveCommits$Worker.run(AsyncReceiveCommits.java:117)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at com.google.gerrit.server.util.RequestScopePropagator.lambda$cleanup$1(RequestScopePropagator.java:212)
	at com.google.gerrit.server.util.RequestScopePropagator.lambda$context$0(RequestScopePropagator.java:191)
	at com.google.gerrit.server.util.ThreadLocalRequestScopePropagator.lambda$wrapImpl$0(ThreadLocalRequestScopePropagator.java:50)
	at com.google.gerrit.server.util.RequestScopePropagator$1.call(RequestScopePropagator.java:94)
	at com.google.gerrit.server.util.RequestScopePropagator$2.run(RequestScopePropagator.java:125)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at com.google.gerrit.server.git.WorkQueue$Task.run(WorkQueue.java:558)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.google.gerrit.server.update.UpdateException: com.google.gerrit.server.git.LockFailureException: Update aborted with one or more lock failures: PackedBatchRefUpdate[
  CREATE: 0000000000000000000000000000000000000000 b1aa33d0bef9336175498a33dd9b1fe90ff3680d refs/changes/74/24974/9  (LOCK_FAILURE)
  UPDATE: 7b45f597f9bf3149c06919e1a1a8bff44de54d67 aba689afe3e0c736a02c05ace6fdf4f452bde5b5 refs/changes/74/24974/meta  (REJECTED_OTHER_REASON: transaction aborted)
]
	at com.google.gerrit.server.update.BatchUpdate.wrapAndThrowException(BatchUpdate.java:233)
	at com.google.gerrit.server.update.NoteDbBatchUpdate.execute(NoteDbBatchUpdate.java:158)
	at com.google.gerrit.server.update.NoteDbBatchUpdate.execute(NoteDbBatchUpdate.java:296)
	at com.google.gerrit.server.update.BatchUpdate.execute(BatchUpdate.java:283)
	at com.google.gerrit.server.git.receive.ReceiveCommits.insertChangesAndPatchSets(ReceiveCommits.java:726)
	... 16 more
Caused by: com.google.gerrit.server.git.LockFailureException: Update aborted with one or more lock failures: PackedBatchRefUpdate[
  CREATE: 0000000000000000000000000000000000000000 b1aa33d0bef9336175498a33dd9b1fe90ff3680d refs/changes/74/24974/9  (LOCK_FAILURE)
  UPDATE: 7b45f597f9bf3149c06919e1a1a8bff44de54d67 aba689afe3e0c736a02c05ace6fdf4f452bde5b5 refs/changes/74/24974/meta  (REJECTED_OTHER_REASON: transaction aborted)
]
	at com.google.gerrit.server.update.RefUpdateUtil.checkResults(RefUpdateUtil.java:77)
	at com.google.gerrit.server.update.RefUpdateUtil.executeChecked(RefUpdateUtil.java:38)
	at com.google.gerrit.server.notedb.NoteDbUpdateManager.execute(NoteDbUpdateManager.java:638)
	at com.google.gerrit.server.notedb.NoteDbUpdateManager.execute(NoteDbUpdateManager.java:604)
	at com.google.gerrit.server.update.NoteDbBatchUpdate$ChangesHandle.execute(NoteDbBatchUpdate.java:353)
	at com.google.gerrit.server.update.NoteDbBatchUpdate.execute(NoteDbBatchUpdate.java:98)
	... 19 more
```

I am restarted the gerrit server, did it help ?

**Comment by vh05** [comment]
I just tried but the error still exists.

```
./rfc.sh 
[detached HEAD aa5e7e893] fuse/liburing: read/write on /dev/fuse using liburing
 Date: Thu Sep 10 14:33:44 2020 +0530
 5 files changed, 668 insertions(+), 270 deletions(-)
Successfully rebased and updated refs/heads/Ganapati_uring.
Enumerating objects: 21, done.
Counting objects: 100% (21/21), done.
Delta compression using up to 2 threads
Compressing objects: 100% (11/11), done.
Writing objects: 100% (11/11), 6.08 KiB | 2.03 MiB/s, done.
Total 11 (delta 7), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (7/7)
remote: Processing changes: updated: 1, refs: 1, done    
To ssh://review.gluster.org/glusterfs
 ! [remote rejected]     HEAD -> refs/for/master/ref-1479 (internal server error: Error inserting change/patchset)
error: failed to push some refs to 'ssh://VHariharmath-rh@review.gluster.org/glusterfs'
```

**Comment by mscherer** [comment]
Ok, so I need to dig more

**Comment by mscherer** [comment]
So, I suspect the problem is a lock file, left after a process crashed. While on it, I also rebooted the server

**Comment by mscherer** [comment]
Ok so does it work now ? (gerrit answer to http and ssh)

**Comment by vh05** [comment]
Yes. It is working no. Let's wait for others and close it

**Comment by mscherer** [comment]
So what I did (for future reference)

- checked the logs
- looked at the git repo, seen a packed-refs.lock file 
- restart the server to make sure there is no git process or anything (+ it was needed)
- remove the .lock file with rm
- run git pack-refs
- restart gerrit, xinetd, httpd, etc

**Comment by rafikc30** [comment]
It also works for me, Thanks @mscherer for your quick action

**Comment by vh05** [comment]
Closing it. Thanks @mscherer
